/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    /**
     * Static initializer block that loads the native 'greetings' library
     * This library contains the C++ implementation of the greetings() method
     * The library name 'greetings' maps to libgreetings.so (Linux) or greetings.dll (Windows)
     */
    static {
        System.loadLibrary("greetings");
    }

    /**
     * Native method declaration
     * This method is implemented in C++ and linked at runtime
     * The actual implementation is in:
     * - app/src/main/cpp/greetings.cpp (for Gradle C++ plugin)
     * - app/src/main/cpp/greetings_cmake.cpp (for CMake build system)
     * 
     * @return A greeting message from native C++ code
     */
    public native String greetings();

    /**
     * Java implementation of a greeting method
     * Returns a static greeting message
     * 
     * @return "Hello World!" string
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Application entry point
     * Demonstrates calling both Java and native methods:
     * 1. getGreeting() - Java method that returns "Hello World!"
     * 2. greetings() - Native C++ method with JNI interface
     * 
     * @param args Command line arguments (not used)
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().greetings());
    }
}
