/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    /**
     * Static initializer - runs when the App class is loaded into memory.
     * Loads the native library 'greetings' into the JVM.
     * The library name 'greetings' maps to libgreetings.so on Linux.
     * This must be called before any native methods can be invoked.
     */
    static {
        System.loadLibrary("greetings");
    }

        /**
     * Native method compiled by Gradle C++ plugin.
     * Implementation is in app/src/main/cpp/greetings.cpp
     * JNI automatically maps this method to the C++ function:
     * Java_org_example_App_greetingFromGradle()
     * @return greeting message from Gradle-compiled C++ code
     */
    public native String greetingFromGradle();

    /**
     * Native method compiled by CMake build system.
     * Implementation is in app/src/main/cpp/greetings_cmake.cpp
     * JNI automatically maps this method to the C++ function:
     * Java_org_example_App_greetingFromCMake()
     * @return greeting message from CMake-compiled C++ code
     */
    public native String greetingFromCMake();

    /**
     * Java implementation of a greeting method
     * Returns a static greeting message
     * 
     * @return "Hello World!" string
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Application entry point
     * Demonstrates calling both Java and native methods from both build systems:
     * 1. getGreeting() - Java method that returns "Hello World!"
     * 2. greetingFromGradle() - Native method compiled by Gradle C++ plugin
     * 3. greetingFromCMake() - Native method compiled by CMake build system
     * 
     * @param args Command line arguments (not used)
     */
    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        System.out.println(app.greetingFromGradle());
        System.out.println(app.greetingFromCMake());
    }
}
