/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    /**
     * Static initializer - runs when the App class is loaded into memory.
     * Loads TWO SEPARATE native libraries:
     * 1. libgreetingsGradle.so - Contains greetingFromGradle() function
     * 2. libgreetingsCMake.so - Contains greetingFromCMake() function
     * 
     * Each library is built by a different build system:
     * - libgreetingsGradle.so: Built by Gradle C++ Plugin (app/build.gradle)
     * - libgreetingsCMake.so: Built by CMake (CMakeLists.txt)
     * 
     * Library names map to:
     * - 'greetingsGradle' → libgreetingsGradle.so on Linux
     * - 'greetingsCMake' → libgreetingsCMake.so on Linux
     * 
     * Both must be loaded before native methods can be invoked.
     */
    static {
        // Load Gradle-compiled library (contains greetingFromGradle function)
        System.loadLibrary("greetingsGradle");
        
        // Load CMake-compiled library (contains greetingFromCMake function)
        System.loadLibrary("greetingsCMake");
    }

    /**
     * Native method compiled by Gradle C++ plugin.
     * Implementation: app/src/main/cpp/greetings.cpp
     * Library: libgreetingsGradle.so (built by Gradle)
     * 
     * JNI automatically maps this method to the C++ function:
     * Java_org_example_App_greetingFromGradle()
     * 
     * @return greeting message from Gradle-compiled C++ code
     */
    public native String greetingFromGradle();

    /**
     * Native method compiled by CMake build system.
     * Implementation: app/src/main/cpp/greetings_cmake.cpp
     * Library: libgreetingsCMake.so (built by CMake)
     * 
     * JNI automatically maps this method to the C++ function:
     * Java_org_example_App_greetingFromCMake()
     * 
     * @return greeting message from CMake-compiled C++ code
     */
    public native String greetingFromCMake();

    /**
     * Java implementation of a greeting method
     * Returns a static greeting message
     * 
     * @return "Hello World!" string
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Application entry point
     * Demonstrates calling both Java and native methods from both build systems:
     * 1. getGreeting() - Java method that returns "Hello World!"
     * 2. greetingFromGradle() - Native method compiled by Gradle C++ plugin
     * 3. greetingFromCMake() - Native method compiled by CMake build system
     * 
     * @param args Command line arguments (not used)
     */
    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        System.out.println(app.greetingFromGradle());
        System.out.println(app.greetingFromCMake());
    }
}
